name: CI/CD Pipeline - Build and Deploy

on:
  push:
    # Trigger on pushes to the main branch
    branches:
      - main

# Define environment variables
env:
  # GitHub Container Registry (GHCR)
  REGISTRY: ghcr.io
  # The tag used for the image
  DOCKER_IMAGE_TAG: aroy-web-app:latest 
  # Note: The 'aroy-web-app' name is derived from your container name

jobs:
  # ----------------------------------------------------------------------
  # 1. CI Job: Build and Push Docker Image to GHCR
  # ----------------------------------------------------------------------
  build-and-push:
    runs-on: ubuntu-latest
    
    # Permissions required to read code and write to the package registry
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        # 💡 FIX: Set up Buildx, which is required by the push action
        uses: docker/setup-buildx-action@v3 

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        # 🚀 FIX: Corrected action name from 'build-and-push-action' to 'build-push-action'
        uses: docker/build-push-action@v5 
        with:
          context: . # Uses the Dockerfile in the root of the repo
          push: true
          # Full image path: ghcr.io/<owner>/<repo>:<tag>
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_TAG }}
          # Enable caching to speed up subsequent builds
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ----------------------------------------------------------------------
  # 2. CD Job: Deploy to Remote Server via SSH
  # ----------------------------------------------------------------------
  deploy:
    # This job only runs after the 'build-and-push' job is successful
    needs: build-and-push 
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        # Use a reliable SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          # Use GitHub Secrets for secure connection information
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 # Change if your SSH port is different
          
          # Commands to execute on the remote server
          script: |
            # Set the deployment path on your server
            REMOTE_DIR=/var/www/aroy-app/
            mkdir -p $REMOTE_DIR
            cd $REMOTE_DIR
            
            # Log in to GHCR on the remote server using a Personal Access Token
            # This token must have the 'read:packages' scope.
            echo "${{ secrets.GHCR_PAT }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
            
            # Define the full image path
            IMAGE_PATH=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_TAG }}

            # Pull the newly built image
            docker pull $IMAGE_PATH

            # Restart the containers using the existing docker-compose.yml file
            # This assumes you have copied your docker-compose.yml to $REMOTE_DIR 
            # and updated it to use the full image path (IMAGE_PATH).
            docker-compose up -d --force-recreate
            
            echo "Deployment successful."
