name: CI/CD for Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # crucial to fix git exit code 128

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages    # Branch for GitHub Pages
          publish_dir: ./             # Folder to deploy (root)
          force_orphan: true          # Creates branch if it doesn't exist
          commit_message: "Deploy static site from GitHub Actions"
