name: CI/CD Pipeline - Build and Deploy

on:
  push:
    branches:
      - main # Triggers on push to the main branch

# Define global environment variables
env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE_TAG: aroy-web-app:latest 
  REMOTE_DIR: /var/www/aroy-app/

jobs:
  # ----------------------------------------------------------------------
  # 1. CI Job: Build and Push Docker Image
  # ----------------------------------------------------------------------
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5 
        with:
          context: . 
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ----------------------------------------------------------------------
  # 2. CD Job: Deploy to Remote Server
  # ----------------------------------------------------------------------
  deploy:
    needs: build-and-push 
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository (Needed to copy docker-compose.yml)
        uses: actions/checkout@v4
      
      # 💡 FIX FOR 'missing server host': Map secrets to explicit environment variables
      # This ensures the host, username, and key are reliably accessible.
      - name: Set SSH Environment Variables
        shell: bash
        run: |
          echo "SSH_HOST_ENV=${{ secrets.SSH_HOST }}" >> $GITHUB_ENV
          echo "SSH_USERNAME_ENV=${{ secrets.SSH_USERNAME }}" >> $GITHUB_ENV
          echo "SSH_PRIVATE_KEY_ENV=${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
          
      # Step A: Ensure the deployment directory exists on the remote server
      - name: Prepare Remote Deployment Directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          # Using the reliable environment variables
          host: ${{ env.SSH_HOST_ENV }}
          username: ${{ env.SSH_USERNAME_ENV }}
          key: ${{ env.SSH_PRIVATE_KEY_ENV }}
          script: |
            mkdir -p ${{ env.REMOTE_DIR }}
            
      # Step B: Copy the docker-compose.yml file to the remote server
      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@v0.1.7 
        with:
          # Using the reliable environment variables
          host: ${{ env.SSH_HOST_ENV }}
          username: ${{ env.SSH_USERNAME_ENV }}
          key: ${{ env.SSH_PRIVATE_KEY_ENV }}
          source: 'docker-compose.yml' 
          target: ${{ env.REMOTE_DIR }}
          
      # Step C: Execute Deployment Commands via SSH
      - name: Run Deployment Script via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          # Using the reliable environment variables
          host: ${{ env.SSH_HOST_ENV }}
          username: ${{ env.SSH_USERNAME_ENV }}
          key: ${{ env.SSH_PRIVATE_KEY_ENV }}
          port: 22
          
          script: |
            # 1. Move to the directory containing the docker-compose.yml
            cd ${{ env.REMOTE_DIR }}
            
            # 2. Log in to GHCR 
            echo "${{ secrets.GHCR_PAT }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
            
            # 3. Define the full image path
            IMAGE_PATH=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_TAG }}

            echo "Pulling image: $IMAGE_PATH"
            docker pull $IMAGE_PATH
            
            # 4. Restart the containers
            docker-compose up -d --force-recreate
            
            echo "Deployment successful on remote server."
