name: Deploy Static Site

on:
  push:
    branches:
      - main  # Deploy only when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages       # branch to deploy
          publish_dir: ./                # folder containing index.html
          force_orphan: true             # ensures clean branch
